---
title: Hello, World!
---

#+BEGIN_SRC haskell
  main :: IO ()
  main = putStrLn "Hello, World!"
#+END_SRC

So, a blog you say?

It has been my intention for a long time to setup a static home page where I can
publish articles and share thoughts. Unfortunately I haven't prioritized this
high enough and so it has taken me a lot longer than what I would have liked.

I've been shopping around for static site generators, briefly trying out
=JavaScript= and =NodeJS= based options before finally settling on [[https://jaspervdj.be/hakyll/][Hakyll]]. The
main motivation for this is that I have a fondness for functional programming
and always liked Haskell. Alas, I have not been able to use it for work and
neither that much for personal projects. The only way to get better at Haskell
and purely functional programming is to use purely functional languages, so this
is a start.

Hakyll uses [[http://pandoc.org/][Pandoc]] to render all kinds of markup formats, including [[http://orgmode.org/][Org]]. Last
Christmas[fn:1] I decided to spend the holiday trying out
[[http://spacemacs.org/][Spacemacs]]. Being a long-time =Vim= user I had never really considered switching
to =Emacs=, but *The Internet™* persuaded me to try due to =Evil= mode and it's
(allegedly) awesome =Vim= emulation. Well, it's been almost a year now and I
have not looked back. Why am I telling you this!? Well, being a recent =Emacs=
convertite, I've naturally also stumbled on =Org=. Writing =Org= in =Emacs= is
far superior to using e.g. =Markdown=, in my opinion[fn:2].

I don't have very large expectations of putting out article after article in a
regular fashion, but hopefully I'll get some sporadic inspirations motivating me
to write.

** Footnotes

[fn:1] ♬ I gave you my heart... ♬

[fn:2] Blog posts can easily start out from a simple capture, or a note
taken from my cell phone. A perfect topic for an upcoming post!
