name: "Build GitHub Pages"

on:
  push:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: myme
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Static Site
      run: |
        nix build .#site
        # Fix nix permissions (https://github.com/actions/deploy-pages/issues/58)
        cp --recursive --dereference --no-preserve=mode,ownership result public
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload entire repository
        path: './public'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
