name: "Build"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: myme
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build Docker image
      run: nix build
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Push image to Docker Hub
      run: |
        docker load < result
        docker tag myme.no:latest myme/myme.no:latest
        docker push myme/myme.no:latest
